services:
  slack-bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7.0.10-alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: