services:
  slack-bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: poetry run gunicorn -c backend/wsgi.py
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7.0.10-alpine
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - slack-bot
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend:
    driver: bridge